### PR TITLE
fix(rule): reset transform-state in multi-match

### LINKED ISSUE #132: [Bug] Transformation state leakage between iterations in evaluateWithMultiMatch
### Description
  When iterating over collection-type variables (such as ``ARGS``) in ``evaluateWithMultiMatch``, transformation-related intermediate state (``transform_list`` and ``transformed_value``) is not always cleared between iterations. Under certain execution paths, this stale state can leak into the next iteration and pollute the ``matched_var`` constructed for a subsequent successful match.

  As a result, the transformation metadata stored in ``matched_var`` may not correspond to the actual variable that triggered the rule match.

### Steps to Reproduce
1. In ``evaluateWithMultiMatch``, iterate over a collection-type variable and evaluate each ``result[i]``.
2. For a specific iteration ``result[i]``:
    - One or more transformation functions are successfully executed.
    - ``transform_list`` and ``transformed_value`` are populated.
    - The rule evaluation ultimately does **not** match.
3. For the next iteration ``result[i+1]``:
   - The rule evaluation **does** match.
   - A ``matched_var`` is constructed and pushed to the result set.
4. Inspect the ``transform_list_`` and ``transformed_value_`` stored in ``matched_var``
### Expected Behavior
  Transformation state must be isolated per ``result[i]`` iteration.
``matched_var`` should only contain transformation data that belongs to the **currently** matched variable.
No residual transformation state from previous, non-matching iterations should be carried over.

### Screenshots
N/A

### Environment
- Operating System: Ubuntu 20.04
- Project Version: 332454a3e3e77bfaa0d7ed473e01689989e23b6b

### Additional Information
N/A

### PR DESCRIPTION
**Pull request by IYanyaning**
When evaluating collection-type variables in evaluateWithMultiMatch, the transformation-related intermediate state (transform_list and transformed_value) could persist across iterations under certain execution paths.

If a previous iteration executed transformations but did not produce a match, the stale transformation state could leak into the next iteration and pollute the matched_var constructed for a subsequent successful match.

This change ensures that transformation state is properly isolated and reset per iteration, so matched_var only contains transformation data corresponding to the variable that actually triggered the match.

Fixes #132

### CODE REVIEW

File: src/rule.cc [hunk 1]
```diff
@@ -588,6 +588,8 @@ bool Rule::evaluateWithMultiMatch(Transaction& t) const {
     for (size_t i = 0; i < result.size();) {
       if (evaluated_value == nullptr) {
         evaluated_value = &result[i];
+        transformed_value.clear();
```
Comment (zhouyujt) [inline src/rule.cc]: You are right, it is necessary to perform clear at the result level here. However, we can remove the clear operation at the upper variable level. Please remove the redundant clear operation at the upper level.

**Review by zhouyujt — APPROVED** [review]
